[package]
name = "serde_ron"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.8"
ron = "0.8.0"
serde = { version = "1.0.183", features = ["derive"] }
